### PR TITLE
Added the health check for Service Fabric on premise AD

### PR DESCRIPTION
**Pull request by pregress**
It uses the service account of the octopus server to authenticate against AD. 

Since Calamari.Azure/Scripts/AzureServiceFabricContext.ps1 also uses `$ClusterConnectionParameters["WindowsCredential"] = $true`

### CODE REVIEW

**Comment by thebigmoosey** [comment]
Thanks @pregress :) This corresponds nicely with the `AzureServiceFabricContext.ps1` code path that was added to unblock AD customers, and this doesn't introduce risk imo because this will only be used by customers who have set that security mode variable manually (so this saves them from using a custom version of Calamari)

**Comment by pregress** [comment]
You're welcome !
@thebigmoosey how can we set the SecurityMode if it's not available in the UI ?
Should we update it in the database or can we update it via the API ?

**Comment by thebigmoosey** [comment]
@pregress We don't officially support AD as a security mode for SF, that's why it's not available as an option in our UI or docs. We have an [existing issue here](https://github.com/OctopusDeploy/Issues/issues/5073) that you can track to be notified when a fix is available, but until then, you'd have to experiment.

I don't believe this is possible with our API currently as the validators would stop any unsupported security-mode values, so you'd be left experimenting with the database values directly, which we obviously do not recommend. If you need this (and the other security methods are not an option), I'd recommend commenting on that other issue describing your needs and the team could continue the conversation there.

**Comment by pregress** [comment]
Wouldn't recommend updating the database. Following exceptions is shown in octopus UI.
Because the `Octopus.Core.Resources.AzureServiceFabricSecurityMode` doesn't contain an enum value for `SecureAD`


```
Octopus v2018.12.0

Error converting value "SecureAD" to type 'Octopus.Core.Resources.AzureServiceFabricSecurityMode'. Path 'SecurityMode', line 1, position 249.
Newtonsoft.Json.JsonSerializationException
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Nevermore.Serialization.InheritedClassConverterBase`2.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Nevermore.RelationalTransaction.Stream
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Octopus.Core.RelationalStorage.Caching.NonCloningFullTableCache.GetTableInternal[T](IRelationalTransaction trn, ValueTuple`2 latestAndCount)
   at Octopus.Core.RelationalStorage.Caching.NonCloningFullTableCache.GetTable[T](IRelationalTransaction trn, ValueTuple`2 latestAndCount, Func`2 filter)
   at Octopus.Core.RelationalStorage.Caching.NonCloningFullTableCache.Get[T](IRelationalTransaction trn, Func`2 filter)
   at Octopus.Server.Web.Api.Actions.MachineRolesListAllAction.ExecuteRegistered()
   at Octopus.Server.Web.Infrastructure.Api.Responder`1.Respond(TDescriptor options, NancyContext context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Octopus.Server.Web.Infrastructure.OctopusNancyModule.<>c__DisplayClass14_0.<get_Routes>b__1(Object x)
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)

--Inner Exception--
Requested value 'SecureAD' was not found.
System.ArgumentException
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Boolean disallowValue, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
```

**Pull request merged**
